apiVersion: v1
kind: Pod
metadata:
  name: exp-workload
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "type"
                operator: In
                values:
                  - "virtual-kubelet"
  tolerations:
    - key: "virtual-kubelet.io/provider"
      operator: "Equal"
      value: "mock"
      effect: "NoSchedule"
  containers:
    - name: exp-workload
      image: ubuntu
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      command:
        - sleep
        - "36000"