- name: stop virtual-kubelet
  systemd:
    name: virtual-kubelet
    state: stopped
    enabled: no

- name: "remove virtual-kubelet.service"
  command: "rm -rf /etc/systemd/system/virtual-kubelet.service"

- name: "remove /etc/virtual-kubelet"
  command: "rm -rf /etc/virtual-kubelet"

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: make sure Collector service is really running
  command: systemctl reset-failed